name: swiftly_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^14.2.0

  # State management
  flutter_riverpod: ^2.5.1

  # Networking
  dio: ^5.5.0       # Best HTTP client
  http: ^1.2.0      # Alternative simpler client
  flutter_dotenv: ^5.1.0  # For environment variables

  # JSON handling
  json_annotation: ^4.8.1

  # Secure storage (auth tokens)
  flutter_secure_storage: ^9.2.2

  # Form validation
  form_builder_validators: ^11.0.0

  # UI helpers
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1

  shared_preferences: ^2.2.2
  country_code_picker: ^3.0.0  # For country code selection in phone number input
  pin_code_fields: ^8.0.1 # For OTP input fields

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.4.9
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700